Fixed exception in email parsing
```
data/error_reports/2020-07-16:08:03:16.670749
CURRENT ENGINE: Engine (ace-ashland1.local - ace)
CURRENT ANALYSIS TARGET: RootAnalysis(dce51dfb-6d90-4aef-b888-7ba59c921f7d)
CURRENT ANALYSIS MODE: email
EXCEPTION
'NoneType' object has no attribute 'encode'

STACK TRACE
Traceback (most recent call last):
  File "/opt/ace/saq/observables/__init__.py", line 1001, in create_observable
    return o_class(o_value, time=o_time)
  File "/opt/ace/saq/observables/__init__.py", line 690, in __init__
    super().__init__(F_EMAIL_ADDRESS, *args, **kwargs)
  File "/opt/ace/saq/observables/__init__.py", line 74, in __init__
    raise ObservableValueError("invalid type {}".format(type(self.value)))
saq.observables.ObservableValueError: invalid type <class 'NoneType'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ace/saq/engine/__init__.py", line 2653, in execute_module_analysis
    analysis_result = analysis_module.analyze(work_item.observable, final_analysis_mode)
  File "/opt/ace/saq/modules/__init__.py", line 800, in analyze
    analysis_result = self.execute_analysis(obj)
  File "/opt/ace/saq/modules/email.py", line 1906, in execute_analysis
    return self.analyze_rfc822(_file)
  File "/opt/ace/saq/modules/email.py", line 1387, in analyze_rfc822
    from_address = analysis.add_observable(F_EMAIL_ADDRESS, address)
  File "/opt/ace/saq/analysis/__init__.py", line 1022, in add_observable
    return self._add_observable_by_spec(*args, **kwargs)
  File "/opt/ace/saq/analysis/__init__.py", line 1049, in _add_observable_by_spec
    observable = self.root.record_observable_by_spec(o_type, o_value, o_time=o_time)
  File "/opt/ace/saq/analysis/__init__.py", line 2997, in record_observable_by_spec
    observable = create_observable(o_type, o_value, o_time=o_time)
  File "/opt/ace/saq/observables/__init__.py", line 1003, in create_observable
    logging.debug("invalid value {} for observable type {}: {}".format(o_value.encode('unicode_escape'), o_type, e))
AttributeError: 'NoneType' object has no attribute 'encode'
```

`File "/opt/ace/saq/modules/email.py", line 1387, in analyze_rfc822`

Which is this snip:

```python
        if 'from' in target_email:
            email_details[KEY_FROM] = decode_rfc2822(target_email['from'])

            address = normalize_email_address(email_details[KEY_FROM])
            if address != '':
                mail_from = address
                from_address = analysis.add_observable(F_EMAIL_ADDRESS, address)
                if from_address:
                    from_address.add_tag('mail_from')
```

Double use of '<<' and '>>'

`From: removed comment <<person@example.com>>`

It looks like someone tried to fix this before but didn't account for error happening before the fix was reached.

```python
def normalize_email_address(email_address):
    """Returns a normalized version of email address.  Returns None if the address cannot be parsed."""
    name, address = parseaddr(email_address)
    if address is '':
        return None

    address = address.strip()

    while address and address.startswith('<'):
        address = address[1:]

    while address and address.endswith('>'):
        address = address[:-1]

    if not address:
        return None

    return address.lower()
```

**The problem is in the python standard email lib use above.** At least, I consider it a problem but I haven't read rfc822 to see if they can claim that. I didn't see an issue for this in the python tracker.. I will try and come back to open one.

```python
>>> from email.utils import parseaddr
>>>
>>> email_address = 'Hippo Steve <<person@example.com>>'
>>> name, address = parseaddr(email_address)
>>> name
'Hippo Steve'
>>> address
''
```

```python
    if address is '':
        # attempt to fix known cases the stdlib has, like <<person@example.com>>
        while email_address and '<<' and '>>'  in email_address:
            email_address = email_address.replace('<<','<').replace('>>','>')
        name, address = parseaddr(email_address)
        if address is '':
            return None
```

and `if address is not None:` instead of `if address != '':` in the EmailAnalyzer